# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
sudo: false
dist: precise
language: c


cache:
  directories:
   - $HOME/.stack
   - $HOME/.cabal
   - $HOME/.ghc
   - $HOME/apt
   - $HOME/.local/bin
   - $HOME/slugs-master

addons:
  apt:
    sources:
     - hvr-ghc
     - ubuntu-toolchain-r-test
    packages:
     - ghc-8.0.1
     - libboost-all-dev
     - g++-4.9
     - cabal-install-1.24
     - alex-3.1.7
     - happy-1.19.5

before_install:
 # Setup tools
 - bash scripts/setup.sh
 - export GHCVER=8.0.1
 - export CABALVER=1.24
 - export HAPPYVER=1.19.5
 - export ALEXVER=3.1.7
 - export PATH=~/.local/bin:$PATH
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH

install:
 - ghc --version
 - g++ --version
 - z3 --version
 - cabal --version
 - happy --version
 - alex --version
 - travis_retry cabal update -v

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal check
 - cabal new-build
 - cd examples && make gen

# EOF

