# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
sudo: false
dist: precise
language: c


cache:
  directories:
   - $HOME/.stack
   - $HOME/.cabal
   - $HOME/.ghc
   - $HOME/apt
   - $HOME/.local/bin
   - $HOME/slugs-master

addons:
  apt:
    sources:
     - hvr-ghc
     - ubuntu-toolchain-r-test
    packages:
     - ghc-8.0.1
     - libboost-all-dev
     - g++-4.9

before_install:
 # Setup tools
 - bash scripts/setup.sh
 - export GHCVER=8.0.1
 - export PATH=~/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ghc --version
 - g++ --version
 - z3 --version

install:
 - stack --no-terminal install --only-dependencies

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - stack --no-terminal build
 - stack --no-terminal exec -- salty -h
 - cd examples && STACK_YAML=../stack.yaml SLUGS=~/slugs-master/src/slugs make gen

# EOF

