# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
sudo: false
language: c

cache:
  directories:
   - $HOME/.stack
   - apt

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - ghc-8.0.1
     - libboost-all-dev
     - g++-4.9

before_install:
 # Download and unpack the stack executable
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - wget https://github.com/VerifiableRobotics/slugs/archive/master.zip
 - unzip master.zip
 - cd slugs-master/src && make
 - find . -name "slugs"

install:
 - stack --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - stack build
 - stack exec -- salty -h
 - find . -name "slugs"
 - cd examples && STACK_YAML=../stack.yaml SLUGS=../slugs-master/src/slugs make

# EOF

