packages:
- .
extra-deps:
    - alex-tools-0.3
    - layout-rules-0.1.0.1
    - git: https://github.com/GaloisInc/language-slugs
      commit: 6cc8b70140061c8f05e503ce69a277b537f81d58
    - prettyprinter-1.2.1
    - GraphSCC-1.0.4
    - monadLib-3.9
    - simple-smt-0.9.4
resolver: lts-9.21
