flags: {}
packages:
- location: ./
- location:
    git: https://github.com/GaloisInc/language-slugs
    commit: master
extra-deps:
    - alex-tools-0.2.0.0
    - layout-rules-0.1.0.1
resolver: nightly-2016-07-11
