from enum import Enum

class CooperativeSearch(object):
    
    __slots__ = ["_state", "_table"]
    
    def __init__(self):
        self._state = 36
    
    class Behavior_1(Enum):
        SEARCH1_1 = 0
        SEARCH2_1 = 1
        TRACK_1 = 2
        RETURN_1 = 3
    
    class Behavior_2(Enum):
        SEARCH1_2 = 0
        SEARCH2_2 = 1
        TRACK_2 = 2
        RETURN_2 = 3
    
    _table = [ {
        (False,False,False,False): (0, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH2_2,False,False)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (3, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,False,False)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (6, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,False)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (9, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,False)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (0, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH2_2,False,False)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (3, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,False,False)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (6, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,False)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (9, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,False)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (0, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH2_2,False,False)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (3, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,False,False)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (6, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,False)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (9, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,False)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (0, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH2_2,False,False)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (3, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,False,False)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (6, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,False)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (9, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,False)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (12, (Behavior_1.SEARCH2_1,Behavior_2.SEARCH2_2,False,True)),
            (False,False,False,True): (1, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,False): (13, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,False,True)),
            (False,False,True,True): (14, (Behavior_1.SEARCH2_1,Behavior_2.TRACK_2,False,True)),
            (False,True,False,False): (15, (Behavior_1.SEARCH2_1,Behavior_2.RETURN_2,False,True)),
            (False,True,False,True): (4, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,False): (16, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (False,True,True,True): (17, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,False,True)),
            (True,False,False,False): (18, (Behavior_1.RETURN_1,Behavior_2.SEARCH2_2,False,True)),
            (True,False,False,True): (7, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,False): (19, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,False,True,True): (20, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,False,True)),
            (True,True,False,False): (21, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,False,True): (10, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,False): (22, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
            (True,True,True,True): (23, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,False,True)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (24, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,False,True): (25, (Behavior_1.TRACK_1,Behavior_2.TRACK_2,True,False)),
            (False,False,True,False): (2, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,False,True,True): (26, (Behavior_1.TRACK_1,Behavior_2.SEARCH1_2,True,False)),
            (False,True,False,False): (27, (Behavior_1.SEARCH1_1,Behavior_2.RETURN_2,True,False)),
            (False,True,False,True): (28, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,False): (5, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (False,True,True,True): (29, (Behavior_1.TRACK_1,Behavior_2.RETURN_2,True,False)),
            (True,False,False,False): (30, (Behavior_1.RETURN_1,Behavior_2.SEARCH1_2,True,False)),
            (True,False,False,True): (31, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,False): (8, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,False,True,True): (32, (Behavior_1.RETURN_1,Behavior_2.TRACK_2,True,False)),
            (True,True,False,False): (33, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,False,True): (34, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,False): (11, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
            (True,True,True,True): (35, (Behavior_1.RETURN_1,Behavior_2.RETURN_2,True,False)),
        },
        {
        (False,False,False,False): (0, (Behavior_1.SEARCH1_1,Behavior_2.SEARCH2_2,False,False)),
        },
        ]
    
    def move(self, recalled_1, recalled_2, inRange_1_3, inRange_2_3):
        try:
            table = self._table[self._state]
            newState,res = table[(recalled_1,recalled_2,inRange_1_3,inRange_2_3)]
            self._state = newState
            return { "behavior_1": res[0],
              "behavior_2": res[1],
              "reg1": res[2],
              "reg2": res[3],
            }
        
        except IndexError:
            raise Exception("Unrecognized internal state: " + str(self._state))
        
        except Exception:
            self._error(recalled_1,recalled_2,inRange_1_3,inRange_2_3)
    
    def _error(self, recalled_1, recalled_2, inRange_1_3, inRange_2_3):
        raise ValueError("Unrecognized input: " + ( "recalled_1 = {recalled_1}; "
                                                        "recalled_2 = {recalled_2}; "
                                                        "inRange_1_3 = {inRange_1_3}; "
                                                        "inRange_2_3 = {inRange_2_3}; ").format( recalled_1=recalled_1,
                                                        recalled_2=recalled_2,
                                                        inRange_1_3=inRange_1_3,
                                                        inRange_2_3=inRange_2_3))