from enum import Enum

class RunningLights(object):
    
    def __init__(self):
        self._state = 128
    
    _table = [ {
        (False,False): (0, (False,False,True,False,False,False,False,False,False,False)),
            (False,True): (1, (False,False,True,False,False,False,False,False,False,False)),
            (True,False): (2, (False,False,True,False,False,False,False,False,False,False)),
            (True,True): (3, (False,False,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (4, (False,True,True,False,False,False,False,False,False,False)),
            (False,True): (5, (False,True,True,False,False,False,False,False,False,False)),
            (True,False): (6, (False,True,True,False,False,False,False,False,False,False)),
            (True,True): (7, (False,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (0, (False,False,True,False,False,False,False,False,False,False)),
            (False,True): (1, (False,False,True,False,False,False,False,False,False,False)),
            (True,False): (2, (False,False,True,False,False,False,False,False,False,False)),
            (True,True): (3, (False,False,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (4, (False,True,True,False,False,False,False,False,False,False)),
            (False,True): (5, (False,True,True,False,False,False,False,False,False,False)),
            (True,False): (6, (False,True,True,False,False,False,False,False,False,False)),
            (True,True): (7, (False,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (8, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (9, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (10, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (11, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (8, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (9, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (10, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (11, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (8, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (9, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (10, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (11, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (8, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (9, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (10, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (11, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (12, (False,True,False,False,True,False,False,False,False,False)),
            (False,True): (13, (False,True,False,False,True,False,False,False,False,False)),
            (True,False): (14, (False,True,False,False,True,False,False,False,False,False)),
            (True,True): (15, (False,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (12, (False,True,False,False,True,False,False,False,False,False)),
            (False,True): (13, (False,True,False,False,True,False,False,False,False,False)),
            (True,False): (14, (False,True,False,False,True,False,False,False,False,False)),
            (True,True): (15, (False,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (16, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (17, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (18, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (19, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (16, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (17, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (18, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (19, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (20, (False,True,False,False,False,True,False,False,False,False)),
            (False,True): (21, (False,True,False,False,False,True,False,False,False,False)),
            (True,False): (22, (False,True,False,False,False,True,False,False,False,False)),
            (True,True): (23, (False,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (20, (False,True,False,False,False,True,False,False,False,False)),
            (False,True): (21, (False,True,False,False,False,True,False,False,False,False)),
            (True,False): (22, (False,True,False,False,False,True,False,False,False,False)),
            (True,True): (23, (False,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (24, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (25, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (26, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (27, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (24, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (25, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (26, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (27, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (24, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (25, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (26, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (27, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (24, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (25, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (26, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (27, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (24, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (25, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (26, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (27, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (24, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (25, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (26, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (27, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (28, (False,True,False,False,False,False,True,False,False,False)),
            (False,True): (29, (False,True,False,False,False,False,True,False,False,False)),
            (True,False): (30, (False,True,False,False,False,False,True,False,False,False)),
            (True,True): (31, (False,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (28, (False,True,False,False,False,False,True,False,False,False)),
            (False,True): (29, (False,True,False,False,False,False,True,False,False,False)),
            (True,False): (30, (False,True,False,False,False,False,True,False,False,False)),
            (True,True): (31, (False,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (32, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (33, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (34, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (35, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (32, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (33, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (34, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (35, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (32, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (33, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (34, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (35, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (32, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (33, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (34, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (35, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (32, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (33, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (34, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (35, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (32, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (33, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (34, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (35, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (36, (False,True,False,False,False,False,False,True,False,False)),
            (False,True): (37, (False,True,False,False,False,False,False,True,False,False)),
            (True,False): (38, (False,True,False,False,False,False,False,True,False,False)),
            (True,True): (39, (False,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (36, (False,True,False,False,False,False,False,True,False,False)),
            (False,True): (37, (False,True,False,False,False,False,False,True,False,False)),
            (True,False): (38, (False,True,False,False,False,False,False,True,False,False)),
            (True,True): (39, (False,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (40, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (41, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (42, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (43, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (40, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (41, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (42, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (43, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (40, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (41, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (42, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (43, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (40, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (41, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (42, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (43, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (40, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (41, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (42, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (43, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (40, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (41, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (42, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (43, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (44, (False,True,False,False,False,False,False,False,True,False)),
            (False,True): (45, (False,True,False,False,False,False,False,False,True,False)),
            (True,False): (46, (False,True,False,False,False,False,False,False,True,False)),
            (True,True): (47, (False,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (44, (False,True,False,False,False,False,False,False,True,False)),
            (False,True): (45, (False,True,False,False,False,False,False,False,True,False)),
            (True,False): (46, (False,True,False,False,False,False,False,False,True,False)),
            (True,True): (47, (False,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (48, (True,True,False,False,False,False,False,False,True,False)),
            (False,True): (49, (True,True,False,False,False,False,False,False,True,False)),
            (True,False): (50, (True,True,False,False,False,False,False,False,True,False)),
            (True,True): (51, (True,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (48, (True,True,False,False,False,False,False,False,True,False)),
            (False,True): (49, (True,True,False,False,False,False,False,False,True,False)),
            (True,False): (50, (True,True,False,False,False,False,False,False,True,False)),
            (True,True): (51, (True,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (48, (True,True,False,False,False,False,False,False,True,False)),
            (False,True): (49, (True,True,False,False,False,False,False,False,True,False)),
            (True,False): (50, (True,True,False,False,False,False,False,False,True,False)),
            (True,True): (51, (True,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (48, (True,True,False,False,False,False,False,False,True,False)),
            (False,True): (49, (True,True,False,False,False,False,False,False,True,False)),
            (True,False): (50, (True,True,False,False,False,False,False,False,True,False)),
            (True,True): (51, (True,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (48, (True,True,False,False,False,False,False,False,True,False)),
            (False,True): (49, (True,True,False,False,False,False,False,False,True,False)),
            (True,False): (50, (True,True,False,False,False,False,False,False,True,False)),
            (True,True): (51, (True,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (48, (True,True,False,False,False,False,False,False,True,False)),
            (False,True): (49, (True,True,False,False,False,False,False,False,True,False)),
            (True,False): (50, (True,True,False,False,False,False,False,False,True,False)),
            (True,True): (51, (True,True,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (52, (False,True,False,False,False,False,False,False,False,True)),
            (False,True): (53, (False,True,False,False,False,False,False,False,False,True)),
            (True,False): (54, (False,True,False,False,False,False,False,False,False,True)),
            (True,True): (55, (False,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (52, (False,True,False,False,False,False,False,False,False,True)),
            (False,True): (53, (False,True,False,False,False,False,False,False,False,True)),
            (True,False): (54, (False,True,False,False,False,False,False,False,False,True)),
            (True,True): (55, (False,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (56, (True,True,False,False,False,False,False,False,False,True)),
            (False,True): (57, (True,True,False,False,False,False,False,False,False,True)),
            (True,False): (58, (True,True,False,False,False,False,False,False,False,True)),
            (True,True): (59, (True,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (56, (True,True,False,False,False,False,False,False,False,True)),
            (False,True): (57, (True,True,False,False,False,False,False,False,False,True)),
            (True,False): (58, (True,True,False,False,False,False,False,False,False,True)),
            (True,True): (59, (True,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (56, (True,True,False,False,False,False,False,False,False,True)),
            (False,True): (57, (True,True,False,False,False,False,False,False,False,True)),
            (True,False): (58, (True,True,False,False,False,False,False,False,False,True)),
            (True,True): (59, (True,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (56, (True,True,False,False,False,False,False,False,False,True)),
            (False,True): (57, (True,True,False,False,False,False,False,False,False,True)),
            (True,False): (58, (True,True,False,False,False,False,False,False,False,True)),
            (True,True): (59, (True,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (56, (True,True,False,False,False,False,False,False,False,True)),
            (False,True): (57, (True,True,False,False,False,False,False,False,False,True)),
            (True,False): (58, (True,True,False,False,False,False,False,False,False,True)),
            (True,True): (59, (True,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (56, (True,True,False,False,False,False,False,False,False,True)),
            (False,True): (57, (True,True,False,False,False,False,False,False,False,True)),
            (True,False): (58, (True,True,False,False,False,False,False,False,False,True)),
            (True,True): (59, (True,True,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (60, (False,False,False,False,False,False,False,False,False,True)),
            (False,True): (61, (False,False,False,False,False,False,False,False,False,True)),
            (True,False): (62, (False,False,False,False,False,False,False,False,False,True)),
            (True,True): (63, (False,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (60, (False,False,False,False,False,False,False,False,False,True)),
            (False,True): (61, (False,False,False,False,False,False,False,False,False,True)),
            (True,False): (62, (False,False,False,False,False,False,False,False,False,True)),
            (True,True): (63, (False,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (60, (False,False,False,False,False,False,False,False,False,True)),
            (False,True): (61, (False,False,False,False,False,False,False,False,False,True)),
            (True,False): (62, (False,False,False,False,False,False,False,False,False,True)),
            (True,True): (63, (False,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (60, (False,False,False,False,False,False,False,False,False,True)),
            (False,True): (61, (False,False,False,False,False,False,False,False,False,True)),
            (True,False): (62, (False,False,False,False,False,False,False,False,False,True)),
            (True,True): (63, (False,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (64, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (65, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (66, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (67, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (68, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (69, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (70, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (71, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (68, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (69, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (70, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (71, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (68, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (69, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (70, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (71, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (68, (True,False,False,False,False,False,False,False,False,True)),
            (False,True): (69, (True,False,False,False,False,False,False,False,False,True)),
            (True,False): (70, (True,False,False,False,False,False,False,False,False,True)),
            (True,True): (71, (True,False,False,False,False,False,False,False,False,True)),
        },
        {
        (False,False): (72, (True,False,False,False,False,False,False,False,True,False)),
            (False,True): (73, (True,False,False,False,False,False,False,False,True,False)),
            (True,False): (74, (True,False,False,False,False,False,False,False,True,False)),
            (True,True): (75, (True,False,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (72, (True,False,False,False,False,False,False,False,True,False)),
            (False,True): (73, (True,False,False,False,False,False,False,False,True,False)),
            (True,False): (74, (True,False,False,False,False,False,False,False,True,False)),
            (True,True): (75, (True,False,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (72, (True,False,False,False,False,False,False,False,True,False)),
            (False,True): (73, (True,False,False,False,False,False,False,False,True,False)),
            (True,False): (74, (True,False,False,False,False,False,False,False,True,False)),
            (True,True): (75, (True,False,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (72, (True,False,False,False,False,False,False,False,True,False)),
            (False,True): (73, (True,False,False,False,False,False,False,False,True,False)),
            (True,False): (74, (True,False,False,False,False,False,False,False,True,False)),
            (True,True): (75, (True,False,False,False,False,False,False,False,True,False)),
        },
        {
        (False,False): (76, (True,False,False,False,False,False,False,True,False,False)),
            (False,True): (77, (True,False,False,False,False,False,False,True,False,False)),
            (True,False): (78, (True,False,False,False,False,False,False,True,False,False)),
            (True,True): (79, (True,False,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (80, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (81, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (82, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (83, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (76, (True,False,False,False,False,False,False,True,False,False)),
            (False,True): (77, (True,False,False,False,False,False,False,True,False,False)),
            (True,False): (78, (True,False,False,False,False,False,False,True,False,False)),
            (True,True): (79, (True,False,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (80, (True,True,False,False,False,False,False,True,False,False)),
            (False,True): (81, (True,True,False,False,False,False,False,True,False,False)),
            (True,False): (82, (True,True,False,False,False,False,False,True,False,False)),
            (True,True): (83, (True,True,False,False,False,False,False,True,False,False)),
        },
        {
        (False,False): (84, (True,False,False,False,False,False,True,False,False,False)),
            (False,True): (85, (True,False,False,False,False,False,True,False,False,False)),
            (True,False): (86, (True,False,False,False,False,False,True,False,False,False)),
            (True,True): (87, (True,False,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (88, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (89, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (90, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (91, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (84, (True,False,False,False,False,False,True,False,False,False)),
            (False,True): (85, (True,False,False,False,False,False,True,False,False,False)),
            (True,False): (86, (True,False,False,False,False,False,True,False,False,False)),
            (True,True): (87, (True,False,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (88, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (89, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (90, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (91, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (88, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (89, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (90, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (91, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (88, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (89, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (90, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (91, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (88, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (89, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (90, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (91, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (88, (True,True,False,False,False,False,True,False,False,False)),
            (False,True): (89, (True,True,False,False,False,False,True,False,False,False)),
            (True,False): (90, (True,True,False,False,False,False,True,False,False,False)),
            (True,True): (91, (True,True,False,False,False,False,True,False,False,False)),
        },
        {
        (False,False): (92, (True,False,False,False,False,True,False,False,False,False)),
            (False,True): (93, (True,False,False,False,False,True,False,False,False,False)),
            (True,False): (94, (True,False,False,False,False,True,False,False,False,False)),
            (True,True): (95, (True,False,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (96, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (97, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (98, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (99, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (92, (True,False,False,False,False,True,False,False,False,False)),
            (False,True): (93, (True,False,False,False,False,True,False,False,False,False)),
            (True,False): (94, (True,False,False,False,False,True,False,False,False,False)),
            (True,True): (95, (True,False,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (96, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (97, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (98, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (99, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (96, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (97, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (98, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (99, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (96, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (97, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (98, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (99, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (96, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (97, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (98, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (99, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (96, (True,True,False,False,False,True,False,False,False,False)),
            (False,True): (97, (True,True,False,False,False,True,False,False,False,False)),
            (True,False): (98, (True,True,False,False,False,True,False,False,False,False)),
            (True,True): (99, (True,True,False,False,False,True,False,False,False,False)),
        },
        {
        (False,False): (100, (True,False,False,False,True,False,False,False,False,False)),
            (False,True): (101, (True,False,False,False,True,False,False,False,False,False)),
            (True,False): (102, (True,False,False,False,True,False,False,False,False,False)),
            (True,True): (103, (True,False,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (104, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (105, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (106, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (107, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (100, (True,False,False,False,True,False,False,False,False,False)),
            (False,True): (101, (True,False,False,False,True,False,False,False,False,False)),
            (True,False): (102, (True,False,False,False,True,False,False,False,False,False)),
            (True,True): (103, (True,False,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (104, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (105, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (106, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (107, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (104, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (105, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (106, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (107, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (104, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (105, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (106, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (107, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (104, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (105, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (106, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (107, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (104, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (105, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (106, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (107, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (108, (True,False,False,True,False,False,False,False,False,False)),
            (False,True): (109, (True,False,False,True,False,False,False,False,False,False)),
            (True,False): (110, (True,False,False,True,False,False,False,False,False,False)),
            (True,True): (111, (True,False,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (112, (True,True,False,True,False,False,False,False,False,False)),
            (False,True): (113, (True,True,False,True,False,False,False,False,False,False)),
            (True,False): (114, (True,True,False,True,False,False,False,False,False,False)),
            (True,True): (115, (True,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (108, (True,False,False,True,False,False,False,False,False,False)),
            (False,True): (109, (True,False,False,True,False,False,False,False,False,False)),
            (True,False): (110, (True,False,False,True,False,False,False,False,False,False)),
            (True,True): (111, (True,False,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (112, (True,True,False,True,False,False,False,False,False,False)),
            (False,True): (113, (True,True,False,True,False,False,False,False,False,False)),
            (True,False): (114, (True,True,False,True,False,False,False,False,False,False)),
            (True,True): (115, (True,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (112, (True,True,False,True,False,False,False,False,False,False)),
            (False,True): (113, (True,True,False,True,False,False,False,False,False,False)),
            (True,False): (114, (True,True,False,True,False,False,False,False,False,False)),
            (True,True): (115, (True,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (112, (True,True,False,True,False,False,False,False,False,False)),
            (False,True): (113, (True,True,False,True,False,False,False,False,False,False)),
            (True,False): (114, (True,True,False,True,False,False,False,False,False,False)),
            (True,True): (115, (True,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (112, (True,True,False,True,False,False,False,False,False,False)),
            (False,True): (113, (True,True,False,True,False,False,False,False,False,False)),
            (True,False): (114, (True,True,False,True,False,False,False,False,False,False)),
            (True,True): (115, (True,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (112, (True,True,False,True,False,False,False,False,False,False)),
            (False,True): (113, (True,True,False,True,False,False,False,False,False,False)),
            (True,False): (114, (True,True,False,True,False,False,False,False,False,False)),
            (True,True): (115, (True,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (116, (True,False,True,False,False,False,False,False,False,False)),
            (False,True): (117, (True,False,True,False,False,False,False,False,False,False)),
            (True,False): (118, (True,False,True,False,False,False,False,False,False,False)),
            (True,True): (119, (True,False,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (120, (True,True,True,False,False,False,False,False,False,False)),
            (False,True): (121, (True,True,True,False,False,False,False,False,False,False)),
            (True,False): (122, (True,True,True,False,False,False,False,False,False,False)),
            (True,True): (123, (True,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (116, (True,False,True,False,False,False,False,False,False,False)),
            (False,True): (117, (True,False,True,False,False,False,False,False,False,False)),
            (True,False): (118, (True,False,True,False,False,False,False,False,False,False)),
            (True,True): (119, (True,False,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (120, (True,True,True,False,False,False,False,False,False,False)),
            (False,True): (121, (True,True,True,False,False,False,False,False,False,False)),
            (True,False): (122, (True,True,True,False,False,False,False,False,False,False)),
            (True,True): (123, (True,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (120, (True,True,True,False,False,False,False,False,False,False)),
            (False,True): (121, (True,True,True,False,False,False,False,False,False,False)),
            (True,False): (122, (True,True,True,False,False,False,False,False,False,False)),
            (True,True): (123, (True,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (120, (True,True,True,False,False,False,False,False,False,False)),
            (False,True): (121, (True,True,True,False,False,False,False,False,False,False)),
            (True,False): (122, (True,True,True,False,False,False,False,False,False,False)),
            (True,True): (123, (True,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (120, (True,True,True,False,False,False,False,False,False,False)),
            (False,True): (121, (True,True,True,False,False,False,False,False,False,False)),
            (True,False): (122, (True,True,True,False,False,False,False,False,False,False)),
            (True,True): (123, (True,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (120, (True,True,True,False,False,False,False,False,False,False)),
            (False,True): (121, (True,True,True,False,False,False,False,False,False,False)),
            (True,False): (122, (True,True,True,False,False,False,False,False,False,False)),
            (True,True): (123, (True,True,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (0, (False,False,True,False,False,False,False,False,False,False)),
            (False,True): (1, (False,False,True,False,False,False,False,False,False,False)),
            (True,False): (2, (False,False,True,False,False,False,False,False,False,False)),
            (True,True): (3, (False,False,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (124, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (125, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (126, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (127, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (0, (False,False,True,False,False,False,False,False,False,False)),
            (False,True): (1, (False,False,True,False,False,False,False,False,False,False)),
            (True,False): (2, (False,False,True,False,False,False,False,False,False,False)),
            (True,True): (3, (False,False,True,False,False,False,False,False,False,False)),
        },
        {
        (False,False): (124, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (125, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (126, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (127, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (124, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (125, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (126, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (127, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (124, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (125, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (126, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (127, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (124, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (125, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (126, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (127, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (124, (False,True,False,True,False,False,False,False,False,False)),
            (False,True): (125, (False,True,False,True,False,False,False,False,False,False)),
            (True,False): (126, (False,True,False,True,False,False,False,False,False,False)),
            (True,True): (127, (False,True,False,True,False,False,False,False,False,False)),
        },
        {
        (False,False): (12, (False,True,False,False,True,False,False,False,False,False)),
            (False,True): (13, (False,True,False,False,True,False,False,False,False,False)),
            (True,False): (14, (False,True,False,False,True,False,False,False,False,False)),
            (True,True): (15, (False,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (12, (False,True,False,False,True,False,False,False,False,False)),
            (False,True): (13, (False,True,False,False,True,False,False,False,False,False)),
            (True,False): (14, (False,True,False,False,True,False,False,False,False,False)),
            (True,True): (15, (False,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (16, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (17, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (18, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (19, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (16, (True,True,False,False,True,False,False,False,False,False)),
            (False,True): (17, (True,True,False,False,True,False,False,False,False,False)),
            (True,False): (18, (True,True,False,False,True,False,False,False,False,False)),
            (True,True): (19, (True,True,False,False,True,False,False,False,False,False)),
        },
        {
        (False,False): (0, (False,False,True,False,False,False,False,False,False,False)),
        },
        ]
    
    def move(self, button1, button2):
        try:
            table = self._table[self._state]
            newState,res = table[(button1,button2)]
            self._state = newState
            return { "state1": res[0],
              "state2": res[1],
              "led0": res[2],
              "led1": res[3],
              "led2": res[4],
              "led3": res[5],
              "led4": res[6],
              "led5": res[7],
              "led6": res[8],
              "led7": res[9],
            }
        
        except IndexError:
            raise Exception("Unrecognized internal state: " + str(self._state))
        
        except Exception:
            self._error(button1,button2)
    
    def _error(self, button1, button2):
        raise ValueError("Unrecognized input: " + ( "button1 = {button1}; "
                                                        "button2 = {button2}; ").format( button1=button1,
                                                        button2=button2))